require('config.plugins_config.catppuccin')
require('config.plugins_config.nvim-tree')
require('config.plugins_config.lualine')
require('config.plugins_config.treesitter')
require('config.plugins_config.telescope')
require('config.plugins_config.lsp_config')
